#####################################################################
#
# CrossFromMolgenis.R
#
# copyright (c) 2009, Danny Arends
# last modified Fep, 2009
# first written Feb, 2009
# 
# Part of the R/qtl package
# Contains: CrossFromMolgenis
#
######################################################################

######################################################################
#
# CrossFromMolgenis:
#
######################################################################

CrossFromMolgenis <- function(DBpath=NULL,DBmarkerID=297,DBtraitID=181){
	if(is.null(DBpath)){
		molgenispath <- paste("http://celtic.service.rug.nl:8080/molgenis4rsandbox/api/R/")
		
		#load autogenerated R interfaces
		source("http://celtic.service.rug.nl:8080/molgenis4rsandbox/api/R/molgenis4rsandbox/source.R")

		#load dbGG specific extension to ease use of the Data <- DataElement structure as matrices
		source("http://celtic.service.rug.nl:8080/molgenis4rsandbox/api/R/molgenis4rsandbox/R/DataMatrix.R")	
		
		#connect to the server
		MOLGENIS.connect("http://celtic.service.rug.nl:8080/molgenis4rsandbox")
		
	}else{
		molgenispath <- paste(DBpath,"/api/R/",sep="")
		
		#load autogenerated R interfaces
		source(paste(DBpath,"/api/R/xgap/source.R",sep=""))

		#load dbGG specific extension to ease use of the Data <- DataElement structure as matrices
		source(paste(DBpath,"/api/R/xgap/R/DataMatrix.R",sep=""))
		
		#connect to the server
		MOLGENIS.connect(DBpath)		
	}

	#get data from server
	marker_data <- find.datamatrix(id=DBmarkerID) #Markerdata
	trait_data <- find.datamatrix(id=DBtraitID) #Traitdata
	marker_info <- find.marker()
	
	#prepare data for the cross object (we should match which matches which)
	marker_row <- find.data(id=DBmarkerID)["rowtype"]
	marker_col <- find.data(id=DBmarkerID)["coltype"]
	trait_row <- find.data(id=DBtraitID)["rowtype"]
	trait_col <- find.data(id=DBtraitID)["coltype"]
	if(marker_row != "Marker" && marker_col != "Marker"){
		stop("No markers in DBmarkerID")
	}
	if(marker_row != "Marker"){
		marker_data <- t(marker_data)
	}
	if(trait_col != "Individual" && trait_col != "Individual"){
		stop("No Individual in DBtraitID")
	}
	if(trait_col != "Individual"){
		trait_data <- t(trait_data)
	}
	
	#All in expected format
	chr <- marker_info[,"chr"]
	cross <- NULL
	for(i in unique(chr)){
		# for each chromosome do
		matrix <- NULL
		map <- NULL
		names <- NULL
		for(j in which(chr==i)){
			#For all markers on the chromosome do
			matrix <- rbind(matrix,marker_data[j,])
			map <- rbind(map,marker_info[j,"cm"])
		}
		names <- names(marker_data[,1])[which(chr==i)]
		
		#We got everything so lets start adding it to the cross object
		length(cross$geno) <- length(cross$geno)+1
		cross$geno[[i]]$data <- t(matrix)
		colnames(cross$geno[[i]]$data)<- names
		cross$geno[[i]]$map <- as.numeric(t(map))
		names(cross$geno[[i]]$map) <- colnames(cross$geno[[i]]$data)
		#Type of the chromosome should be retrieved from the database
		class(cross$geno[[i]])[1] <- "A"
	}
	names(cross$geno) <- unique(chr)
	cross$pheno <- as.data.frame(t(trait_data[,]))
	#Make it into a crossobject get the kind of cross from the database (RISELF/RISIBL/F2/BC)
	class(cross)[1] <- "riself"
	class(cross)[2] <- "cross"
	cross
}

