#####################################################################
#
# CrossFromMolgenis.R
#
# copyright (c) 2009, Danny Arends
# last modified Fep, 2009
# first written Feb, 2009
# 
# Part of the R/qtl package
# Contains: CrossFromMolgenis
#
######################################################################

######################################################################
#
# CrossFromMolgenis:
#
######################################################################

CrossFromMolgenis <- function(DBmarkerID=297,DBtraitID=181,DBpath="http://celtic.service.rug.nl:8080/molgenis4rsandbox"){
	library("RCurl")
	if(!("RCurl" %in% names( getLoadedDLLs()))){
		stop("Please install the package RCurl from bioconductor to use the molgenis interface\n")
	}
	if(is.null(DBpath)){
		stop("Please provide a valid DBpath\n")
	}else{
		#Set the path to molgenis
		molgenispath <- paste(DBpath,"/api/R/",sep="")
		
		#Source the interface
		source(molgenispath)
		
		#load autogenerated R interfaces
		source(paste(molgenispath,"/xgap/source.R",sep=""))

		#load dbGG specific extension to ease use of the Data <- DataElement structure as matrices
		source(paste(molgenispath,"/xgap/R/DataMatrix.R",sep=""))
		
		#connect to the server
		MOLGENIS.connect(DBpath)		
	}

	#get data from server
	marker_data <- find.datamatrix(id=DBmarkerID) #Markerdata
	trait_data <- find.datamatrix(id=DBtraitID) #Traitdata
	marker_info <- find.marker()
	
	#prepare data for the cross object (we should match which matches which)
	marker_row <- find.data(id=DBmarkerID)["rowtype"]
	marker_col <- find.data(id=DBmarkerID)["coltype"]
	trait_row <- find.data(id=DBtraitID)["rowtype"]
	trait_col <- find.data(id=DBtraitID)["coltype"]
	
	if(marker_row != "Marker" && marker_col != "Marker"){
		stop("No markers in DBmarkerID")
	}
	if(marker_row != "Marker"){
		marker_data <- t(marker_data)
	}
	if(trait_row != "Individual" && trait_col != "Individual"){
		stop("No Individual in DBtraitID")
	}
	if(trait_col != "Individual"){
		trait_data <- t(trait_data)
	}
	cat("Number of individuals in Marker set:",dim(marker_data)[2],"\n")
	cat("Number of individuals in Phenotype set:",dim(trait_data)[2],"\n")
	
	#We assume that if we have IND in markers = IND in trait that individuals match
	if(dim(marker_data)[2] != dim(trait_data)[2]){
		matchV <- match(colnames(trait_data)[1:dim(trait_data)[2]],colnames(marker_data))
		marker_data <- marker_data[,matchV]
	}
	
	#Parse data towards the R/QTL format we need to convert all AA/AB/BB etc to 1,2,3
	for(i in 1:dim(marker_data)[1]) {
		for(j in 1:dim(marker_data)[2]) {
			repl <- FALSE
		    if(is.na(marker_data[i,j])){
				marker_data[i,j] <- NA
				repl <- TRUE
			}
			if(!repl && as.character(marker_data[i,j]) == 'AA'){
				marker_data[i,j] <- 1
				repl <- TRUE
			}
			if(!repl && as.character(marker_data[i,j]) == 'AB'){
				marker_data[i,j] <- 2
				repl <- TRUE
			}
			if(!repl && as.character(marker_data[i,j]) == 'BB'){
				marker_data[i,j] <- 3
				repl <- TRUE
			}
			if(!repl){
				marker_data[i,j] <- 9
			}
		}
	}
	chr <- NULL
	loc <- NULL
	for(i in 1:dim(marker_data)[1]){
		chr <- c(chr,marker_info[which(rownames(marker_data)[i]== marker_info$name),"chr"])
		loc <- c(loc,marker_info[which(rownames(marker_data)[i]== marker_info$name),"cm"])
	}
	#FIX for NA in chromosome
	remFromChr <- NULL
	for(i in 1:length(chr)) {
		if(is.na(chr[i])){
			remFromChr <- c(remFromChr,i)
		}
	}
	chr <- chr[-remFromChr]
	loc <- loc[-remFromChr]
	
	#All in expected format, So we can begin filling our cross object
	cross <- NULL
	for(i in unique(chr)){
		# for each chromosome do
		matrix <- NULL
		map <- NULL
		names <- NULL
		for(j in which(chr==i)){
				#For all markers on the chromosome do
				matrix <- rbind(matrix,marker_data[j,])
				map <- rbind(map,loc[j])
		}
		names <- names(marker_data[,1])[which(chr==i)]

		#We got everything so lets start adding it to the cross object
		length(cross$geno) <- length(cross$geno)+1
		cross$geno[[i]]$data <- t(matrix)
		colnames(cross$geno[[i]]$data)<- names
		cross$geno[[i]]$map <- as.numeric(t(map))
		names(cross$geno[[i]]$map) <- colnames(cross$geno[[i]]$data)
		#Type of the chromosome should be retrieved from the database
		class(cross$geno[[i]])[1] <- "A"
	}
	names(cross$geno) <- unique(chr)
	cross$pheno <- as.data.frame(t(trait_data[,]))
	#Make it into a crossobject get the kind of cross from the database (RISELF/RISIBL/F2/BC)
	class(cross)[1] <- "riself"
	class(cross)[2] <- "cross"
	cross
}

# end of CrossFromMolgenis.R
