#####################################################################
#
# CrossToMolgenis.R
#
# copyright (c) 2009, Danny Arends
# last modified Fep, 2009
# first written Feb, 2009
# 
# Part of the R/qtl package
# Contains: CrossToMolgenis
#
######################################################################

######################################################################
#
# CrossToMolgenis:
#
######################################################################

CrossToMolgenis <- function(DBpath=NULL,intervalQTLmap=NULL){
	if(!("RCurl" %in% names( getLoadedDLLs()))){
		stop("Please install the package RCurl from bioconductor to use the molgenis interface\n")
	}
	if(is.null(DBpath)){
		#Source the interface
		source("http://celtic.service.rug.nl:8080/molgenis4rsandbox/api/R/")
		
		#Set the path to molgenis
		molgenispath <- paste("http://celtic.service.rug.nl:8080/molgenis4rsandbox/api/R/")
		
		#load autogenerated R interfaces
		source("http://celtic.service.rug.nl:8080/molgenis4rsandbox/api/R/molgenis4rsandbox/source.R")

		#load dbGG specific extension to ease use of the Data <- DataElement structure as matrices
		source("http://celtic.service.rug.nl:8080/molgenis4rsandbox/api/R/molgenis4rsandbox/R/DataMatrix.R")	
		
		#connect to the server
		MOLGENIS.connect("http://celtic.service.rug.nl:8080/molgenis4rsandbox")
		
	}else{
		#Source the interface
		source("http://celtic.service.rug.nl:8080/molgenis4rsandbox/api/R/")
		
		#Set the path to molgenis
		molgenispath <- paste(DBpath,"/api/R/",sep="")
		
		#load autogenerated R interfaces
		source(paste(DBpath,"/api/R/xgap/source.R",sep=""))

		#load dbGG specific extension to ease use of the Data <- DataElement structure as matrices
		source(paste(DBpath,"/api/R/xgap/R/DataMatrix.R",sep=""))
		
		#connect to the server
		MOLGENIS.connect(DBpath)		
	}

	#get data from server
	if(is.null(intervalQTLmap)){
		stop("Please supply a QTL interval map\n")
	}
	
	investi <- find.investigation()
	markers <- find.marker()
	
	for(i in 1:dim(intervalQTLmap)[1]) {
		if(!colnames(intervalQTLmap)[i] %in% markers$name){
			add.marker(name=colnames(intervalQTLmap)[i],chr=intervalQTLmap[i,"chr"],cm=intervalQTLmap[i,"pos (Cm)"])
		}
	}
	#Markers are inside molgenis, now we need to get the QTL's in
	class(intervalQTLmap) <- "matrix"
	intervalQTLmap <- cbind(rownames(intervalQTLmap),intervalQTLmap)
	intervalQTLmap <- cbind(intervalQTLmap,rep(investi,dim(intervalQTLmap)[1]))
	colnames(intervalQTLmap) <- c("name","chr","pos","qtl","investigation")
	
	#Push QTL data into molgenis
	add.data(intervalQTLmap)
	
}

