#####################################################################
#
# CrossFromMolgenis.R
#
# copyright (c) 2009, Danny Arends
# last modified Fep, 2009
# first written Feb, 2009
# 
# Part of the R/qtl package
# Contains: CrossFromMolgenis
#
######################################################################

######################################################################
#
# CrossFromMolgenis:
#
######################################################################

CrossFromMolgenis <- function(){
	molgenispath <- paste("http://gbicserver1.biol.rug.nl:8080/molgenis4xgap_lerxcvi/api/R/")

	#load autogenerated R interfaces
	source("http://gbicserver1.biol.rug.nl:8080/molgenis4xgap_lerxcvi/api/R/xgap/source.R")

	#load dbGG specific extension to ease use of the Data <- DataElement structure as matrices
	source("http://gbicserver1.biol.rug.nl:8080/molgenis4xgap_lerxcvi/api/R/xgap/R/DataMatrix.R")

	#connect to the server
	MOLGENIS.connect("http://gbicserver1.biol.rug.nl:8080/molgenis4xgap_lerxcvi")
	marker_data <- find.datamatrix(id=58340) #Markerdata
	trait_data <- find.datamatrix(id=58351) #Traitdata
	marker_info <- find.marker()
	chr <- marker_info[,"chr"]
	cross <- NULL
	for(i in unique(chr)){
		matrix <- NULL
		map <- NULL
		names <- NULL
		for(j in which(chr==i)){
			matrix <- rbind(matrix,marker_data[j,])
			map <- rbind(map,marker_info[j,"cm"])
		}
		names <- names(marker_data[,1])[which(chr==i)]
		length(cross$geno) <- length(cross$geno)+1
		cross$geno[[i]]$data <- t(matrix)
		colnames(cross$geno[[i]]$data)<- names
		cross$geno[[i]]$map <- as.numeric(t(map))
		names(cross$geno[[i]]$map) <- colnames(cross$geno[[i]]$data)
		class(cross$geno[[i]])[1] <- "A"
	}
	names(cross$geno) <- unique(chr)
	cross$pheno <- as.data.frame(t(trait_data[,]))
	class(cross)[1] <- "riself"
	class(cross)[2] <- "cross"
	cross
}

