#####################################################################
#
# PipelineMolgenis.R
#
# copyright (c) 2009, Danny Arends
# last modified Mrt, 2009
# first written Mrt, 2009
# 
# Part of the R/qtl package
# Contains: PipelineMolgenis
#
######################################################################

######################################################################
#
# PipelineMolgenis:
#
######################################################################

PipelineMolgenis <- function(DBmarkerID=298,DBtraitID=181,name="MQMResultsTest",DBpath="http://celtic.service.rug.nl:8080/molgenis4rsandbox",Fupdate=0,...){
	library("RCurl")
	if(!("RCurl" %in% names( getLoadedDLLs()))){
		stop("ERROR: Please install the package RCurl from bioconductor to use the molgenis interface\n")
	}
	if(is.null(DBpath)){
		stop("ERROR: Please provide a valid DBpath\n")
	}else{
		#Set the path to molgenis
		molgenispath <- paste(DBpath,"/api/R/",sep="")
		
		#Source the interface
		source(molgenispath)
		pname <- strsplit(DBpath,"/")[[1]][length(strsplit(DBpath,"/")[[1]])]
		
		cat(paste(molgenispath,pname,"/source.R",sep=""))
		#load autogenerated R interfaces
		source(paste(molgenispath,pname,"/source.R",sep=""))

		#load dbGG specific extension to ease use of the Data <- DataElement structure as matrices
		source(paste(molgenispath,pname,"/R/DataMatrix.R",sep=""))
		
		#connect to the server
		MOLGENIS.connect(DBpath)		
	}
	trait_row <- find.data(id=DBtraitID)["rowtype"]
	trait_col <- find.data(id=DBtraitID)["coltype"]
	trait_info  <- find.data(id=DBtraitID)
	
	if(trait_row != "Individual" && trait_col != "Individual"){
		stop("ERROR: No Individual in DBtraitID")
	}
	
	if(trait_col != "Individual"){
		#traits are in the cols
		num_traits <- as.integer(trait_info["totalcols"])
	}else{
		num_traits <- as.integer(trait_info["totalrows"])
	}
	
	
	for(x in 1:num_traits){
		cat("------------------------------------------------------------------\n")
		cat("Trait",x,"/",num_traits,"\n")
		cat("------------------------------------------------------------------\n")
		cat("INFO:Starting Stage1: Getting information from Molgenis\n")
			cross <- CrossFromMolgenis(DBmarkerID,DBtraitID,trait=x,DBpath)
		cat("INFO:DONE Stage1\n")
		cat("INFO:Starting Stage2: scanning for QTL's\n")
			cross <- fill.geno(cross)
			result <- scanMQM(cross,...,plot=T)
		cat("INFO:DONE Stage2\n")	
		cat("INFO:Stage3: Storing calculated QTL's to Molgenis\n")
			ResultsToMolgenis(result, name,(x-1),DBpath, Fupdate)
		cat("INFO:DONE Stage3\n")
		Sys.sleep(0.1)
	}
}